import type { DashboardData } from "./types";

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 86_400_000).toISOString();

export const demoData: DashboardData = {
  demo: true,
  configured: { database: false, agent: false, email: false },
  searches: [
    {
      id: "demo-search-1",
      name: "Blue Ridge basecamp",
      location: "Asheville, NC + 40 miles",
      property_type: "either",
      min_price: null,
      max_price: 650000,
      min_beds: 2,
      min_acres: 2,
      must_haves: "Mountain view, high-speed internet, no HOA",
      deal_breakers: "Flood zone, steep unpaved access",
      alert_email: "you@example.com",
      active: true,
      created_at: daysAgo(28),
    },
    {
      id: "demo-search-2",
      name: "Vermont cabin",
      location: "Windsor County, VT",
      property_type: "home",
      min_price: 250000,
      max_price: 525000,
      min_beds: 2,
      min_acres: 1,
      must_haves: "Wood stove, privacy, within 25 min of town",
      deal_breakers: "Seasonal road",
      alert_email: "you@example.com",
      active: true,
      created_at: daysAgo(12),
    },
  ],
  listings: [
    {
      id: "demo-listing-1",
      search_id: "demo-search-1",
      title: "Cedar Ridge A-frame",
      address: "Black Mountain, North Carolina",
      price: 589000,
      currency: "USD",
      property_type: "House",
      beds: 3,
      baths: 2,
      acres: 4.8,
      summary: "A quiet ridge property with long-range western views, fiber internet, and usable acreage near town.",
      score: 94,
      pros: ["Fiber internet", "No HOA", "Mountain view"],
      cons: ["Older roof"],
      url: "https://example.com/listing/cedar-ridge",
      image_url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80",
      source: "example.com",
      status: "new",
      first_seen_at: daysAgo(0),
      search: { name: "Blue Ridge basecamp", location: "Asheville, NC + 40 miles" },
    },
    {
      id: "demo-listing-2",
      search_id: "demo-search-2",
      title: "Weathered barn house",
      address: "Woodstock, Vermont",
      price: 479000,
      currency: "USD",
      property_type: "House",
      beds: 2,
      baths: 1.5,
      acres: 3.1,
      summary: "A compact converted barn with a wood stove, meadow, and year-round town-maintained access.",
      score: 87,
      pros: ["12 min to town", "Private meadow", "Wood stove"],
      cons: ["One full bath"],
      url: "https://example.com/listing/barn-house",
      image_url: "https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&w=1200&q=80",
      source: "example.com",
      status: "saved",
      first_seen_at: daysAgo(2),
      search: { name: "Vermont cabin", location: "Windsor County, VT" },
    },
    {
      id: "demo-listing-3",
      search_id: "demo-search-1",
      title: "Creekside modern cabin",
      address: "Old Fort, North Carolina",
      price: 415000,
      currency: "USD",
      property_type: "House",
      beds: 2,
      baths: 2,
      acres: 2.4,
      summary: "Recently built cabin on a wooded creek parcel with simple access to I-40 and a separate studio.",
      score: 81,
      pros: ["Studio", "Usable land", "Recent build"],
      cons: ["No confirmed fiber"],
      url: "https://example.com/listing/creekside",
      image_url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80",
      source: "example.com",
      status: "new",
      first_seen_at: daysAgo(1),
      search: { name: "Blue Ridge basecamp", location: "Asheville, NC + 40 miles" },
    },
  ],
  recentRuns: [
    {
      id: "demo-run-1",
      search_id: "demo-search-1",
      status: "complete",
      found_count: 3,
      error: null,
      started_at: daysAgo(0),
      finished_at: daysAgo(0),
    },
  ],
};
